modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://kubejs.com/support?source=kubejs_thermal&mc=1902&loader=forge"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs_thermal"
version = "${version}"
displayName = "KubeJS Thermal"
authors = "LatvianModder"
description = '''
KubeJS Thermal Expansion integration
'''
license = "GNU LGPLv3"

[[dependencies.kubejs_thermal]]
modId = "kubejs"
mandatory = true
versionRange = "[1902.6.1-build.300,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_thermal]]
modId = "thermal_expansion"
mandatory = true
versionRange = "[1.3.0,)"
ordering = "AFTER"
side = "BOTH"